git:
  depth: 1
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_script:
  - npm install directory-tree remark remark-toc remark-html
script:
  - echo 'XD'
after_success:
  - git clone https://github.com/lib-pku/lib-pku.github.io.git
  - node index.js > lib-pku.github.io/index.html
  - cd lib-pku.github.io
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -m 'Add files via upload'
  - git push https://${DEPLOY_TOKEN}@github.com/lib-pku/lib-pku.github.io.git master -f
